ALTER TABLE Products
MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MODIFY price DECIMAL(10,2) NOT NULL CHECK(price >= 0),
MODIFY status ENUM('ACTIVE', 'INACTIVE', 'DISCONTINUED') NOT NULL default 'ACTIVE',
MODIFY created_at DATETIME DEFAULT current_timestamp,
MODIFY category varchar(100) NOT NULL,
DROP COLUMN temp_note;