CREATE TABLE REVIEW (
 ReviewID INT PRIMARY KEY,
 CustID INT NOT NULL,
 ProductID INT NOT NULL,
 Rating INT NOT NULL CHECK (Rating >= 1 AND Rating <= 5),
 Comment VARCHAR(500),
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
 UNIQUE (CustID, ProductID),
 FOREIGN KEY (CustID) REFERENCES CUSTOMER(CustID),
 FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);